#!/usr/bin/env node
'use strict';

/**
 * report.js
 * Usage: node scripts/report.js <campaign-id>
 * 
 * Generates a markdown summary report for a campaign.
 * Reads call logs from calls.jsonl and queries Supabase for contact stats.
 */

require('dotenv').config({ path: require('path').join(__dirname, '../webhooks/.env') });
const fs = require('fs');
const path = require('path');
const { createClient } = require('@supabase/supabase-js');

const ROOT_DIR = path.join(__dirname, '..');

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const campaignId = process.argv[2];
  if (!campaignId) {
    console.error('Usage: node scripts/report.js <campaign-id>');
    console.error('Example: node scripts/report.js 2026-03-navratri');
    process.exit(1);
  }

  console.log(`\n🪷 Temple Voice — Campaign Report: ${campaignId}`);
  console.log('─'.repeat(50));

  // Load campaign config
  const campaignFile = path.join(ROOT_DIR, 'campaigns', campaignId, 'campaign.json');
  if (!fs.existsSync(campaignFile)) {
    console.error(`❌ Campaign not found: ${campaignFile}`);
    process.exit(1);
  }
  const campaign = JSON.parse(fs.readFileSync(campaignFile, 'utf8'));

  // Read calls.jsonl
  const callsFile = path.join(ROOT_DIR, 'campaigns', campaignId, 'results', 'calls.jsonl');
  const callLogs = [];
  if (fs.existsSync(callsFile)) {
    const lines = fs.readFileSync(callsFile, 'utf8').trim().split('\n').filter(Boolean);
    for (const line of lines) {
      try {
        callLogs.push(JSON.parse(line));
      } catch (e) {
        // Skip malformed lines
      }
    }
  }
  console.log(`   Call logs from file: ${callLogs.length}`);

  // Aggregate from logs
  const fileStats = {};
  let totalDuration = 0;
  const optOuts = [];

  for (const log of callLogs) {
    const d = log.disposition || 'unknown';
    fileStats[d] = (fileStats[d] || 0) + 1;
    totalDuration += log.duration || 0;
    if (log.isOptOut) optOuts.push(log.contactPhone);
  }

  // Query Supabase for authoritative contact stats
  let dbStats = null;
  let totalContacts = 0;

  if (process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY) {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY
    );

    const { data, error } = await supabase
      .from('voice_campaign_contacts')
      .select('status')
      .eq('campaign_id', campaignId);

    if (!error && data) {
      dbStats = {};
      totalContacts = data.length;
      for (const row of data) {
        dbStats[row.status] = (dbStats[row.status] || 0) + 1;
      }
      console.log(`   Supabase contacts: ${totalContacts}`);
    } else if (error) {
      console.warn(`   ⚠️  Supabase query failed: ${error.message}`);
    }
  } else {
    console.warn('   ⚠️  Supabase not configured — report based on call logs only');
  }

  // Generate markdown report
  const now = new Date().toISOString();
  const avgDuration = callLogs.length > 0
    ? Math.round(totalDuration / callLogs.length)
    : 0;

  const stats = dbStats || fileStats;
  const total = totalContacts || callLogs.length;

  const markdown = `# Campaign Report: ${campaign.name}

**Campaign ID:** \`${campaignId}\`  
**Generated:** ${now}  
**Voice Agent:** Arjun (ID: \`${campaign.assistant_id}\`)  
**Calling From:** ${campaign.phone_number}

---

## Summary

| Metric | Value |
|--------|-------|
| Total Contacts | ${total} |
| Pending | ${stats.pending || 0} |
| Called | ${stats.called || 0} |
| Answered | ${stats.answered || 0} |
| Voicemail | ${stats.voicemail || 0} |
| No Answer | ${stats['no-answer'] || 0} |
| Busy | ${stats.busy || 0} |
| Failed | ${stats.failed || 0} |
| Opted Out | ${stats['opted-out'] || 0} |
| Confirmed | ${stats.confirmed || 0} |

---

## Call Log Stats

| Metric | Value |
|--------|-------|
| Total Calls Logged | ${callLogs.length} |
| Avg Call Duration | ${avgDuration}s |
| Opt-Outs | ${optOuts.length} |

---

## Events Promoted

${(campaign.events || []).map(e =>
  `- **${e.name}**: ${e.dates ? e.dates.join(', ') : `${e.start} – ${e.end}`}`
).join('\n')}

---

## Calling Window

- **Timezone:** ${campaign.calling_window?.timezone}
- **Days:** ${(campaign.calling_window?.days || []).join(', ')}
- **Hours:** ${campaign.calling_window?.start_time} – ${campaign.calling_window?.end_time}

---

*Report generated by Temple Voice Platform — 🪷 Built by Brahma for RKT Dallas / JKYog*
`;

  // Save report
  const resultsDir = path.join(ROOT_DIR, 'campaigns', campaignId, 'results');
  fs.mkdirSync(resultsDir, { recursive: true });
  const reportFile = path.join(resultsDir, 'summary.md');
  fs.writeFileSync(reportFile, markdown, 'utf8');

  // Print to console
  console.log('\n' + markdown);
  console.log(`\n✅ Report saved to: ${reportFile}`);
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
